### ISSUE TITLE
Python-created CFG files

### ISSUE THREAD

**Issue by n01r** [hightower8083/PoGit#18]
Hey @hightower8083,

do you think this project could also be feasibly extended to create the CFG files for our runtime parameters?
Especially when varying laser pulses (i.e. energy or shape which changes the initialization time) or when playing with the resolution, the times of the outputs are bothersome to synchronize.
An easy way to calculate all times with respect to, for instance, when the laser pulse maximum would reach the surface of the target would be amazing. :smile: 

We also still have a lot of code duplication for standard output like energy histograms.

Cheers,
Marco

**EDIT**
Ha, I'm seeing that I overlooked that you already started this for the plugins.
My bad. ^^;

**Comment by hightower8083** [comment]
hey Marco,

its just a templater so it can be extended in lots of ways. I'm exclusively using only PoGit for setting building and running the sims, so it has all what's needed for a broad range of situations  (though things like particlefilters, i still add manually)

Yeah, we are already templating `run.cfg` to set grid, decomposition, diags and wall-time.  For now, me and Yang are the only users, so we add only functionality, which we need, though i'd be happy to help with any users requests. Diags are far from complete, but they are easy to develop, and I'll wait till some people start using it before adding on something more advanced.

Concerning the laser injection time,I haven't not really got how this _arrival time_ works, so we've made it into a `cdelay` variable which sets a [delay in meters](https://github.com/hightower8083/PoGit/blob/b60161815501607d5126782f64aa97d795ecf9b1/pogit/laser.py#L96) for the beam center to enter the simulation box, but I'm not sure its defined rigorously enough. May be you can help to debug it in a way you want it to be ? 

Here is the basic [example](https://github.com/hightower8083/PoGit/blob/dev/examples/example_foil2D.py) of foil case, but I've no doubt we can write you a more advance and flexible setup script for you to account for the parameters variations you'll need. If you can provide details on what you want, i'll help you with that.
